//arguably stupid to redo the work that went into drawBasicPlot.C
//but I'm doing it anyway (lots of copy/paste)
//also:
//as much as I hate it, it might be nice to make this macro compilable

//drawNormalized() was used to produce plots of various distributions as generated by basicLoop::cutflowPlotter()
//work in progress: drawStack() to plot data/MC comparisons

//QCD and SingleTop need to be added with hadd

#include "TROOT.h"
#include "TFile.h"
#include "TString.h"
#include "TStyle.h"
#include "TCanvas.h"
#include "TLegend.h"
#include "THStack.h"
#include "TH1.h"

#include "/afs/cern.ch/user/j/joshmt/root/util/HistHolder.h"
//i am using histHolder, but reimplementing a lot of stuff in PlotUtil,etc

#include <iostream>
#include <map>

//holds a list of the sample names (using same code as file name)
std::vector<TString> samples_;
std::map<TString, TFile*> files_;
std::map<TString, UInt_t> sampleColor_;
std::map<TString, TString> sampleLabel_;
std::map<TString, UInt_t> sampleMarkerStyle_;

TString loaded_=""; //bookkeeping

bool customrange_active=false;
double customrange_low=0;
double customrange_high=0;

int rebin_=0;

bool logy_=false;
bool dostack_=false;
bool doleg_=true;

void setPlotRange(double low,double high) {
  customrange_low=low;
  customrange_high=high;
  customrange_active=true;
}

void resetPlotRange() {
  customrange_active=false;
}

void setLogY(bool dolog) {
  logy_=dolog;
}

void setStackMode(bool dostack) {
  dostack_=dostack;
}

void setRebin(int rebin) {
  rebin_=rebin;
}

void resetRebin() {
  setRebin(0);
}

void drawLegend(bool doleg) {
  doleg_=doleg;
}


TFile* fdata=0;
TH1D* hdata=0;
void loadSamples(TString filestub) {
  if (filestub == loaded_) return;
  else if (loaded_ != "") {cout<<"quit root and try again"<<endl; return;}
  loaded_=filestub;
  const TString cutdesc = "Baseline0_PF_pfMEThigh_PFLep_minDP";

  samples_.push_back("QCD");
  samples_.push_back("TTbarJets");
  samples_.push_back("SingleTop");
  samples_.push_back("WJets");
  samples_.push_back("ZJets");
  samples_.push_back("Zinvisible");
  samples_.push_back("LM13");

  sampleColor_["LM13"] = kGray; //borrowed from a different sample
  sampleColor_["QCD"] = kYellow;
  sampleColor_["TTbarJets"]=kRed+1;
  sampleColor_["SingleTop"] = kMagenta;
  sampleColor_["WJets"] = kGreen-3;
  sampleColor_["ZJets"] = kAzure-2;
  sampleColor_["Zinvisible"] = kOrange-3;

  sampleLabel_["LM13"] = "LM13";
  sampleLabel_["QCD"] = "QCD";
  sampleLabel_["TTbarJets"]="t#bar{t}";
  sampleLabel_["SingleTop"] = "Single-Top";
  sampleLabel_["WJets"] = "W#rightarrowl#nu";
  sampleLabel_["ZJets"] = "Z#rightarrowl^{+}l^{-}";
  sampleLabel_["Zinvisible"] = "Z#rightarrow#nu#nu";

  sampleMarkerStyle_["LM13"] = kFullStar;
  sampleMarkerStyle_["QCD"] = kFullCircle;
  sampleMarkerStyle_["TTbarJets"]= kFullSquare;
  sampleMarkerStyle_["SingleTop"] = kOpenSquare;
  sampleMarkerStyle_["WJets"] = kMultiply;
  sampleMarkerStyle_["ZJets"] = kFullTriangleUp;
  sampleMarkerStyle_["Zinvisible"] = kFullTriangleDown;

  for (unsigned int isample=0; isample<samples_.size(); isample++) {
    TString fname=filestub; fname+=".";
    fname+=cutdesc;
    fname+=".";
    fname+=samples_[isample];
    fname+=".root";
    files_[samples_[isample]] = new TFile(fname);
    if (files_[samples_[isample]]->IsZombie() ) cout<<"file error with "<<samples_[isample]<<endl;
    else     cout<<"Added sample: "<<samples_[isample]<<endl;
  }

  //load data file too
  TString dname=filestub; dname+=".";
  dname+=cutdesc;
  dname+=".data.root";
  if (dname.Contains("_NoTrigger"))   dname.ReplaceAll("_NoTrigger","");
  if (dostack_) {
    fdata = new TFile(dname);
    if (fdata->IsZombie()) cout<<"Problem with data file! "<<dname<<endl;
  }

}

TCanvas* cnorm;
TLegend* leg;
THStack* thestack;
void drawNormalized(const TString hname, const TString xtitle, const TString ytitle)
{

  gROOT->SetStyle("CMS");

  if (dostack_)  loadSamples("Nminus1plots");
  else   loadSamples("cutflowPlots");
  
  cnorm= new TCanvas("cnorm","normalized",600,400);
  cnorm->cd()->SetRightMargin(0.04);

  if (logy_) cnorm->SetLogy();

  leg = new TLegend(0.696, 0.35, 0.94, 0.92);
  leg->SetBorderSize(0);
  //leg->SetFillColor(0);
  //leg->SetLineColor(1);
  leg->SetLineStyle(0);
  leg->SetTextFont(42);
  leg->SetFillStyle(0);

  if (dostack_)  thestack = new THStack("thestack","--");

  //first load the desired histogram from each file
  HistHolder hh;
  TString opt="hist e";
  for (unsigned int isample=0; isample<samples_.size(); isample++) {
    cout <<samples_[isample]<<endl;
    hh.load(hname,files_[samples_[isample]]);
    hh.find(hname,files_[samples_[isample]])->SetXTitle(xtitle);
    hh.find(hname,files_[samples_[isample]])->SetYTitle(ytitle);

    if (customrange_active) {
      hh.find(hname,files_[samples_[isample]])->GetXaxis()->SetRangeUser(customrange_low,customrange_high);
    }
    if (rebin_!=0)    hh.find(hname,files_[samples_[isample]])->Rebin(rebin_);

    if (!dostack_) {
      //set line color instead of fill color for this type of plot
      hh.find(hname,files_[samples_[isample]])->SetLineColor(sampleColor_[samples_[isample]]);
      hh.find(hname,files_[samples_[isample]])->SetMarkerStyle(sampleMarkerStyle_[samples_[isample]]);
      hh.find(hname,files_[samples_[isample]])->SetMarkerColor(sampleColor_[samples_[isample]]);
      
      //ad hoc additions
      hh.find(hname,files_[samples_[isample]])->SetLineWidth(2);
      hh.find(hname,files_[samples_[isample]])->SetMarkerColor(sampleColor_[samples_[isample]]);
    }
    else {
      hh.find(hname,files_[samples_[isample]])->SetFillColor(sampleColor_[samples_[isample]]);
    }

    leg->AddEntry( hh.find(hname,files_[samples_[isample]]), sampleLabel_[samples_[isample]]);

    if (dostack_) {
      thestack->Add( hh.find(hname,files_[samples_[isample]]) );
    }
    else {
      hh.find(hname,files_[samples_[isample]])->Draw(opt);
      if (!opt.Contains("same")) opt+=" same";
    }
  }

  if (!dostack_) {
    hh.normalize(); //normalize all histos to 1
    hh.SetMaximum( hh.GetMaximum()*1.05);
  }
  else {
    thestack->Draw("hist");
    thestack->GetHistogram()->GetXaxis()->SetTitle(xtitle);
    thestack->GetHistogram()->GetYaxis()->SetTitle(ytitle);
    if (customrange_active) {
      thestack->GetHistogram()->GetXaxis()->SetRangeUser(customrange_low,customrange_high);
    }

    hdata = (TH1D*) fdata->Get(hname);
    hdata->UseCurrentStyle();
    hdata->SetMarkerColor(kBlack);
    hdata->SetLineWidth(2);
    hdata->SetMarkerStyle(kFullCircle);
    hdata->SetMarkerSize(1);
    if (rebin_!=0)  hdata->Rebin(rebin_);
    hdata->Draw("SAME");
    cout<<hdata->GetMaximum()<<"\t"<<thestack->GetMaximum()<<endl;
    if (hdata->GetMaximum() > thestack->GetMaximum()) {
      thestack->SetMaximum( hdata->GetMaximum());
    }
  }

  if (doleg_)  leg->Draw();

  TString savename = hname;
  if (logy_) savename += "-logY";
  if (!dostack_)    savename += "-drawNormalized";
  else savename += "-drawStack";

  //amazingly, \includegraphics cannot handle an extra dot in the filename. so avoid it.
  cnorm->SaveAs(savename+".eps"); //for me
  //  cnorm->Print(savename+".C");    //for formal purposes
  cnorm->SaveAs(savename+".pdf"); //for pdftex
  cnorm->SaveAs(savename+".png"); //for twiki

}

void plotStuff()
{
  //this first one is not so informative because of HT=0 events
  drawNormalized("H_HT_cutInclusive","HT [GeV]","Arbitrary units");
  drawNormalized("H_NJets_cutHT","# of jets","Arbitrary units");

  setPlotRange(0,5);
  drawNormalized("H_NElectrons_cut3Jets","# of electrons","Arbitrary units");
  drawNormalized("H_NMuons_cut3Jets","# of muons","Arbitrary units");

  resetPlotRange();
  drawNormalized("H_MET_cutMuVeto","E^{miss}_{T} [GeV]","Arbitrary units");

  setRebin(2);
  drawNormalized("H_minDeltaPhi_cutMET","#Delta #phi_{min}","Arbitrary units");
  resetRebin();

  setPlotRange(0,5);
  drawNormalized("H_NBJets_cutMET","# of b-tagged jets","Arbitrary units");
  drawNormalized("H_NBJets_cutDeltaPhi","# of b-tagged jets","Arbitrary units");

}

void plotOtherStuff()
{

  setStackMode(true);

  setPlotRange(40,260);
  setLogY(true);
  drawNormalized("H_MET","MET [GeV]","Events");

  drawNormalized("H_MET_ge1b","MET [GeV]","Events");
  drawNormalized("H_MET_ge2b","MET [GeV]","Events");

  //
  setStackMode(true); //once per session
  //
  setPlotRange(150,1200);
  setRebin(10);
  drawNormalized("H_HT","HT (GeV)","Events");

  setPlotRange(0,8);
  resetRebin();
  drawNormalized("Hnjets","# of jets","Events");
  drawNormalized("Hnjets_ge1b","# of jets","Events");
  drawNormalized("Hnjets_ge2b","# of jets","Events");

  setPlotRange(0,3);
  drawNormalized("HnElectrons","# of electrons","Events");
  drawNormalized("HnElectrons_ge1b","# of electrons","Events");
  drawNormalized("HnElectrons_ge2b","# of electrons","Events");

  drawNormalized("HnMuons","# of muons","Events");
  drawNormalized("HnMuons_ge1b","# of muons","Events");
  drawNormalized("HnMuons_ge2b","# of muons","Events");

  setPlotRange(0,260);
  setLogY(true);
  drawNormalized("H_MET","E_{T}^{miss}","Events");
  drawNormalized("H_MET_ge1b","E_{T}^{miss}","Events");
  drawNormalized("H_MET_ge2b","E_{T}^{miss}","Events");

  setLogY(false);
  resetPlotRange();
  setRebin(10);
  drawNormalized("H_METphi","#phi of E_{T}^{miss}","Events");


  setRebin(2);
  setLogY(true);
  drawLegend(false);
  drawNormalized("HminDeltaPhiMETj","min(#Delta#phi[ jets 1..3, E_{T}^{miss} ] )","Events");

  drawNormalized("HminDeltaPhiMETj_ge1b","min(#Delta#phi[ jets 1..3, E_{T}^{miss} ] )","Events");
  setLogY(false);
  drawLegend(true);
  drawNormalized("HminDeltaPhiMETj_ge1b","min(#Delta#phi[ jets 1..3, E_{T}^{miss} ] )","Events");

  setPlotRange(0,4);
  resetRebin();
  drawNormalized("Hnbjets","# of b-tagged jets","Events");


  resetPlotRange();
  setRebin(4);
  drawNormalized("Hjetpt1","p_{T} of lead jet","Events");
  drawNormalized("Hjetpt1_ge1b","p_{T} of lead jet","Events");
  drawNormalized("Hjetpt1_ge2b","p_{T} of lead jet","Events");

  drawNormalized("Hjetphi1","#phi of lead jet","Events");
  drawNormalized("Hjetphi1_ge1b","#phi of lead jet","Events");
  drawNormalized("Hjetphi1_ge2b","#phi of lead jet","Events"); //why are 2 events at the same phi?

  drawNormalized("Hjeteta1","#eta of lead jet","Events");
  drawNormalized("Hjeteta1_ge1b","#eta of lead jet","Events");
  drawNormalized("Hjeteta1_ge2b","#eta of lead jet","Events");

  drawNormalized("Hbjetpt1_ge1b","p_{T} of lead b-tagged jet","Events");
  drawNormalized("Hbjetpt1_ge2b","p_{T} of lead b-tagged jet","Events");

}
