/// -*- C++ -*-
//
/*
SupplementaryNtuple

A class to make flat ntuples
Intended to supplement the ntuples generated by MakeTopologyNtuple in EJetMET_CU/Top_electron_jets
*/

//
// Original Author:  Joshua Thompson
// $Id:$
//

class SupplementaryNtuple : public edm::EDAnalyzer {
  
 public:
  explicit SupplementaryNtuple(const edm::ParameterSet&);
  ~SupplementaryNtuple();

protected:
  int findSUSYMaternity( const reco::Candidate & cand ) ;

 private:
  virtual void beginJob() ;
  virtual void analyze(const edm::Event&, const edm::EventSetup&);
  virtual void endJob() ;

  //gen particles!
  edm::InputTag genParticles_;

  //also add trigger info, eventually
  //form would be a std::vector of strings (names) and vector of bits

  TTree *susytree_;

  //data members to hold ntuple info
  // -- note: we want to be careful to avoid name conflicts with the MakeTopologyNtuple variables
  // -- hence, the prefix SUSY_

  Int_t SUSY_nb;
  //we could and probably should add much more information here
  //but for now this is sufficient

};
